language: csharp
solution: MTAServiceStatus.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore MTAServiceStatus.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll
  
